version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    container_name: postgres_pgvector
    restart: always
    environment:
      POSTGRES_DB: rag_db
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
